---
title: "p1_soupx"
author: "Anindita Brahma"
date: "03/06/2022"
output: html_document
---

```{r setup, include=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}
libraries <- c("dplyr", "Seurat",
               "SoupX", "patchwork",
               "DropletUtils", "ggplot2",
               "hdf5r")
for (lib in libraries) {
  if (require(package = lib, character.only = TRUE)) {
    message("Library loaded: ", lib)
  } else {
    print("Installing")
    BiocManager::install(lib, Ncpus = 10, update = TRUE)
    library(lib, character.only = TRUE)
    message("Library loaded: ", lib)
  }
}
sessionInfo()
for (package in (.packages())) {
  print(paste("Package", package, "version", packageVersion(package)))
}
```

#Using SoupX on P1 cellranger_v6.1.2 count
##useful link: https://cran.r-project.org/web/packages/SoupX/vignettes/pbmcTutorial.html

```{r}
#import raw and filtered matrices from cellranger count output
raw_matrix <- Read10X_h5(filename = "input/raw_feature_bc_matrix.h5")
filtered_matrix <- Read10X_h5(filename = "input/filtered_feature_bc_matrix.h5")
filtered_matrix[("ObirOr5-Orco"), 1:30]
str(raw_matrix)
str(filtered_matrix)

##link: https://broadinstitute.github.io/2019_scWorkshop/data-wrangling-scrnaseq.html

counts_per_nuclei <- Matrix::colSums(filtered_matrix)
counts_per_gene <- Matrix::rowSums(filtered_matrix)
genes_per_nuclei <- Matrix::colSums(filtered_matrix > 0)
nuclei_per_gene <- Matrix::rowSums(filtered_matrix > 0)
plot(sort(genes_per_nuclei), xlab = 'nuclei', log = 'y',
     main = 'genes per nuclei (ordered)')



#create a seurat object
filtered_matrix_seurat <- CreateSeuratObject(counts = filtered_matrix)

##create clusters with seurat object
filtered_matrix_seurat <- SCTransform(filtered_matrix_seurat, verbose = FALSE)
filtered_matrix_seurat <- RunPCA(filtered_matrix_seurat, verbose = FALSE)
filtered_matrix_seurat <- RunUMAP(filtered_matrix_seurat, dims = 1:30, verbose = FALSE)
filtered_matrix_seurat <- FindNeighbors(filtered_matrix_seurat, dims = 1:30, verbose = FALSE)
filtered_matrix_seurat <- FindClusters(filtered_matrix_seurat, verbose = TRUE)
filtered_matrix_seurat <- RunTSNE(filtered_matrix_seurat, dims = 1:30, verbose = FALSE)

DimPlot(filtered_matrix_seurat, reduction = "umap")
DimPlot(filtered_matrix_seurat, reduction = "tsne")

# 
# cluster4_markers <- FindMarkers(filtered_matrix_seurat, ident.1 = 4,
#                                 min.pct = 0.25)
# head(cluster4_markers)
# 
# VlnPlot(filtered_matrix_seurat, features = "ObirOr5-Orco")
FeaturePlot(filtered_matrix_seurat, features = c("ObirOr5-Orco", "ObirOr5-U22",
                                                 "ObirOr5-U61", "ObirOr5-V23",
                                                 "ObirOr5-V18", "ObirOr5-V24",
                                                 "ObirOr5-V21", "ObirOr5-V15"),
            reduction = "tsne")

FeaturePlot(filtered_matrix_seurat, features = c("LOC105287628", "LOC105284892",
                                                 "LOC105283549"))
FeaturePlot(filtered_matrix_seurat, features = c("LOC105286785", "LOC105284919",
                                                 "LOC105284916", "ObirOr5-Orco"))
VlnPlot(object = filtered_matrix_seurat,
        features = c("LOC105286785", "LOC105284919",
                     "LOC105284916", "ObirOr5-Orco"))
#neuronal markers
FeaturePlot(filtered_matrix_seurat, features = c("LOC105284919", "LOC105276401",
                                                 "LOC105285306", "LOC105275115",
                                                 "LOC105280759"),
            reduction = "tsne")


#get number of nuclei expressing a gene
sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")["ObirOr5-Orco", ] > 0)
sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")["ObirOr5-9E14", ] > 0)
sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")["ObirOr5-L29", ] > 0)
sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")[c("ObirOr5-9E29", "ObirOr5-L29"), ] > 0)

sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")["LOC105286785", ] > 0) ##repo ortholog

sum(GetAssayData(object = filtered_matrix_seurat,
                 slot = "data")["LOC105284916", ] > 0) ##nSyb ortholog




# FeaturePlot(filtered_matrix_seurat, features = "Doublet_score")



##create a soup channel with raw and fileterd matirces
soup_channel <- SoupChannel(tod = raw_matrix, toc = filtered_matrix)
soup_channel

#add clustering data to soupchannel
filtered_matrix_seurat_meta <- filtered_matrix_seurat@meta.data
filtered_matrix_seurat_umap <- filtered_matrix_seurat@reductions$umap@cell.embeddings
soup_channel <- setClusters(sc = soup_channel, setNames(filtered_matrix_seurat_meta$seurat_clusters,
                                                        rownames(filtered_matrix_seurat_meta)))
soup_channel <- setDR(soup_channel, filtered_matrix_seurat_umap)
head(filtered_matrix_seurat_meta)


##estimating contamination
sc_contamination <- setContaminationFraction(sc = soup_channel,
                                             contFrac = 0.1,
                                             forceAccept = TRUE)
sc_auto <- autoEstCont(sc = soup_channel,
                       tfidfMin = 0.5, forceAccept = TRUE)

head(soup_channel$soupProfile[order(soup_channel$soupProfile$est,
                                    decreasing = TRUE), ], n = 20)

plotMarkerDistribution(sc = soup_channel)

orco <- plotMarkerMap(soup_channel, "ObirOr5-Orco")
plot(orco)

orv21 <- plotMarkerMap(soup_channel, "ObirOr5-V21")
plot(orv21)

oru22 <- plotMarkerMap(soup_channel, "ObirOr5-U22")
plot(oru22)

nsyb <- plotMarkerMap(soup_channel, "LOC105284919")
plot(nsyb)

probable_repo_ortholog <- plotMarkerMap(soup_channel, "LOC105286785")
plot(probable_repo_ortholog)

##estimating non expressing cells
use_to_estimate <- estimateNonExpressingCells(sc = soup_channel,
                                              nonExpressedGeneList = list(OR = or_genes),
                                              clusters = FALSE)
plotMarkerMap(sc = soup_channel,
              geneSet = or_genes, useToEst = use_to_estimate)

##calculating contamination fraction

soup_channel <- calculateContaminationFraction(sc = soup_channel,
                                          list(OR = or_genes),
                                          useToEst = use_to_estimate,
                                          forceAccept = TRUE)

head(soup_channel$metaData)

##correcting expression profile
out <- adjustCounts(sc = soup_channel)

cntSoggy <- rowSums(soup_channel$toc > 0)
cntStrained <- rowSums(out > 0)
mostZeroed <- tail(sort((cntSoggy - cntStrained)/cntSoggy),
                   n = 20)
mostZeroed

tail(sort(rowSums(soup_channel$toc > out)/rowSums(soup_channel$toc > 0)),
     n = 20)

plotChangeMap(sc = soup_channel, cleanedMatrix = out, "ObirOr5-Orco")


```

```{r}
##normalize the seurat object
filtered_matrix_normalized <- NormalizeData(filtered_matrix_seurat,
                                            normalization.method = "LogNormalize",
                                            scale.factor = 10000)
##get nuclei expressing specific genes
orco <- GetAssayData(object = filtered_matrix_normalized,
                     assay = "RNA", slot = "data")["ObirOr5-Orco", ]
head(orco, 10)

#here nuclei identities are rownames; convert that into a column
orco_df <- data.frame(orco)
orco_nuclei_id <- rownames(orco_df)
rownames(orco_df) <- NULL

orco_df <- cbind(orco_nuclei_id, orco_df)
colnames(orco_df) <- c("nuclei_id_orco", "orco_count")

orco_subset <- subset(x = orco_df, subset = count > 2)



```

```{r}
#OR gene set
or_genes <- c("ObirOr5-9E1",
"ObirOr5-9E10",
"ObirOr5-9E100",
"ObirOr5-9E101",
"ObirOr5-9E102",
"ObirOr5-9E103",
"ObirOr5-9E104",
"ObirOr5-9E105PSE",
"ObirOr5-9E106",
"ObirOr5-9E107",
"ObirOr5-9E108",
"ObirOr5-9E109",
"ObirOr5-9E11",
"ObirOr5-9E110",
"ObirOr5-9E111",
"ObirOr5-9E112",
"ObirOr5-9E113",
"ObirOr5-9E114",
"ObirOr5-9E115",
"ObirOr5-9E116",
"ObirOr5-9E117",
"ObirOr5-9E118",
"ObirOr5-9E119",
"ObirOr5-9E12",
"ObirOr5-9E120",
"ObirOr5-9E121",
"ObirOr5-9E122",
"ObirOr5-9E123PSE",
"ObirOr5-9E124",
"ObirOr5-9E125",
"ObirOr5-9E126",
"ObirOr5-9E127",
"ObirOr5-9E128",
"ObirOr5-9E129",
"ObirOr5-9E13",
"ObirOr5-9E130PSE",
"ObirOr5-9E131",
"ObirOr5-9E132",
"ObirOr5-9E133",
"ObirOr5-9E134",
"ObirOr5-9E135CTE",
"ObirOr5-9E136",
"ObirOr5-9E137",
"ObirOr5-9E138",
"ObirOr5-9E139",
"ObirOr5-9E14",
"ObirOr5-9E140",
"ObirOr5-9E141",
"ObirOr5-9E142PSE",
"ObirOr5-9E143PSE",
"ObirOr5-9E144PSE",
"ObirOr5-9E145PSE",
"ObirOr5-9E146PSE",
"ObirOr5-9E147PSE",
"ObirOr5-9E148",
"ObirOr5-9E149PSE",
"ObirOr5-9E15",
"ObirOr5-9E150",
"ObirOr5-9E151",
"ObirOr5-9E152",
"ObirOr5-9E153PSE",
"ObirOr5-9E154",
"ObirOr5-9E155",
"ObirOr5-9E156",
"ObirOr5-9E157",
"ObirOr5-9E158",
"ObirOr5-9E159",
"ObirOr5-9E16",
"ObirOr5-9E160",
"ObirOr5-9E161",
"ObirOr5-9E162",
"ObirOr5-9E163PSE",
"ObirOr5-9E164",
"ObirOr5-9E165",
"ObirOr5-9E166",
"ObirOr5-9E167",
"ObirOr5-9E168",
"ObirOr5-9E169",
"ObirOr5-9E17",
"ObirOr5-9E170",
"ObirOr5-9E171",
"ObirOr5-9E172",
"ObirOr5-9E173",
"ObirOr5-9E174",
"ObirOr5-9E175",
"ObirOr5-9E176",
"ObirOr5-9E177",
"ObirOr5-9E178PSE",
"ObirOr5-9E179",
"ObirOr5-9E18",
"ObirOr5-9E180",
"ObirOr5-9E181",
"ObirOr5-9E182",
"ObirOr5-9E183PSE",
"ObirOr5-9E184",
"ObirOr5-9E185",
"ObirOr5-9E186",
"ObirOr5-9E187PSE",
"ObirOr5-9E188",
"ObirOr5-9E189",
"ObirOr5-9E19",
"ObirOr5-9E190",
"ObirOr5-9E191",
"ObirOr5-9E192",
"ObirOr5-9E193",
"ObirOr5-9E194",
"ObirOr5-9E195",
"ObirOr5-9E196",
"ObirOr5-9E197",
"ObirOr5-9E198",
"ObirOr5-9E199PSE",
"ObirOr5-9E20",
"ObirOr5-9E200",
"ObirOr5-9E201",
"ObirOr5-9E202",
"ObirOr5-9E203",
"ObirOr5-9E204",
"ObirOr5-9E205",
"ObirOr5-9E206",
"ObirOr5-9E207",
"ObirOr5-9E208",
"ObirOr5-9E209",
"ObirOr5-9E21",
"ObirOr5-9E210",
"ObirOr5-9E211",
"ObirOr5-9E212",
"ObirOr5-9E213",
"ObirOr5-9E214",
"ObirOr5-9E215",
"ObirOr5-9E216",
"ObirOr5-9E217",
"ObirOr5-9E218",
"ObirOr5-9E219",
"ObirOr5-9E22",
"ObirOr5-9E220",
"ObirOr5-9E221",
"ObirOr5-9E222",
"ObirOr5-9E223",
"ObirOr5-9E224",
"ObirOr5-9E225",
"ObirOr5-9E226",
"ObirOr5-9E227",
"ObirOr5-9E228",
"ObirOr5-9E229",
"ObirOr5-9E23",
"ObirOr5-9E230",
"ObirOr5-9E231",
"ObirOr5-9E232",
"ObirOr5-9E233",
"ObirOr5-9E234PSE",
"ObirOr5-9E235PSE",
"ObirOr5-9E236PSE",
"ObirOr5-9E237PSE",
"ObirOr5-9E238",
"ObirOr5-9E239",
"ObirOr5-9E240PSE",
"ObirOr5-9E241",
"ObirOr5-9E242",
"ObirOr5-9E243",
"ObirOr5-9E244",
"ObirOr5-9E245",
"ObirOr5-9E246",
"ObirOr5-9E247",
"ObirOr5-9E248",
"ObirOr5-9E249",
"ObirOr5-9E24PSE",
"ObirOr5-9E25",
"ObirOr5-9E250",
"ObirOr5-9E251",
"ObirOr5-9E252PSE",
"ObirOr5-9E253PSE",
"ObirOr5-9E254",
"ObirOr5-9E255",
"ObirOr5-9E256",
"ObirOr5-9E257",
"ObirOr5-9E258",
"ObirOr5-9E259",
"ObirOr5-9E26",
"ObirOr5-9E260",
"ObirOr5-9E261",
"ObirOr5-9E262PSE",
"ObirOr5-9E263",
"ObirOr5-9E264PSE",
"ObirOr5-9E265PSE",
"ObirOr5-9E266PSE",
"ObirOr5-9E267",
"ObirOr5-9E268",
"ObirOr5-9E269",
"ObirOr5-9E27",
"ObirOr5-9E270",
"ObirOr5-9E271",
"ObirOr5-9E272",
"ObirOr5-9E273",
"ObirOr5-9E274",
"ObirOr5-9E275",
"ObirOr5-9E276",
"ObirOr5-9E277",
"ObirOr5-9E278",
"ObirOr5-9E279",
"ObirOr5-9E28",
"ObirOr5-9E280",
"ObirOr5-9E281",
"ObirOr5-9E282PSE",
"ObirOr5-9E283",
"ObirOr5-9E284",
"ObirOr5-9E285",
"ObirOr5-9E286",
"ObirOr5-9E287",
"ObirOr5-9E288",
"ObirOr5-9E289",
"ObirOr5-9E29",
"ObirOr5-9E290",
"ObirOr5-9E291",
"ObirOr5-9E292",
"ObirOr5-9E293",
"ObirOr5-9E294",
"ObirOr5-9E295",
"ObirOr5-9E296",
"ObirOr5-9E297",
"ObirOr5-9E298",
"ObirOr5-9E299",
"ObirOr5-9E2PSE",
"ObirOr5-9E30",
"ObirOr5-9E300",
"ObirOr5-9E301",
"ObirOr5-9E302",
"ObirOr5-9E303",
"ObirOr5-9E304",
"ObirOr5-9E305",
"ObirOr5-9E306",
"ObirOr5-9E307",
"ObirOr5-9E308",
"ObirOr5-9E309",
"ObirOr5-9E31",
"ObirOr5-9E310",
"ObirOr5-9E311",
"ObirOr5-9E312",
"ObirOr5-9E313",
"ObirOr5-9E314PSE",
"ObirOr5-9E315",
"ObirOr5-9E316",
"ObirOr5-9E317",
"ObirOr5-9E318",
"ObirOr5-9E319",
"ObirOr5-9E32",
"ObirOr5-9E320",
"ObirOr5-9E321",
"ObirOr5-9E322",
"ObirOr5-9E323",
"ObirOr5-9E324",
"ObirOr5-9E325",
"ObirOr5-9E326",
"ObirOr5-9E327",
"ObirOr5-9E328",
"ObirOr5-9E329",
"ObirOr5-9E33",
"ObirOr5-9E330",
"ObirOr5-9E331",
"ObirOr5-9E332",
"ObirOr5-9E333",
"ObirOr5-9E334",
"ObirOr5-9E335",
"ObirOr5-9E336",
"ObirOr5-9E337",
"ObirOr5-9E338",
"ObirOr5-9E339",
"ObirOr5-9E34",
"ObirOr5-9E340",
"ObirOr5-9E341PSE",
"ObirOr5-9E342",
"ObirOr5-9E343",
"ObirOr5-9E344",
"ObirOr5-9E345",
"ObirOr5-9E346",
"ObirOr5-9E347",
"ObirOr5-9E348",
"ObirOr5-9E349",
"ObirOr5-9E35",
"ObirOr5-9E350",
"ObirOr5-9E351",
"ObirOr5-9E352",
"ObirOr5-9E353",
"ObirOr5-9E354PSE",
"ObirOr5-9E36",
"ObirOr5-9E37",
"ObirOr5-9E38",
"ObirOr5-9E39PSE",
"ObirOr5-9E3PSE",
"ObirOr5-9E4",
"ObirOr5-9E40PSE",
"ObirOr5-9E41",
"ObirOr5-9E42",
"ObirOr5-9E43",
"ObirOr5-9E44",
"ObirOr5-9E45",
"ObirOr5-9E46",
"ObirOr5-9E47",
"ObirOr5-9E48",
"ObirOr5-9E49",
"ObirOr5-9E5",
"ObirOr5-9E50",
"ObirOr5-9E51",
"ObirOr5-9E52",
"ObirOr5-9E53PSE",
"ObirOr5-9E54",
"ObirOr5-9E55",
"ObirOr5-9E56",
"ObirOr5-9E57",
"ObirOr5-9E58",
"ObirOr5-9E59",
"ObirOr5-9E6",
"ObirOr5-9E60",
"ObirOr5-9E61",
"ObirOr5-9E62",
"ObirOr5-9E63PSE",
"ObirOr5-9E64",
"ObirOr5-9E65",
"ObirOr5-9E66",
"ObirOr5-9E67",
"ObirOr5-9E68",
"ObirOr5-9E69",
"ObirOr5-9E7",
"ObirOr5-9E70",
"ObirOr5-9E71",
"ObirOr5-9E72PSE",
"ObirOr5-9E73",
"ObirOr5-9E74",
"ObirOr5-9E75",
"ObirOr5-9E76",
"ObirOr5-9E77",
"ObirOr5-9E78",
"ObirOr5-9E79",
"ObirOr5-9E8",
"ObirOr5-9E80",
"ObirOr5-9E81",
"ObirOr5-9E82",
"ObirOr5-9E83",
"ObirOr5-9E84",
"ObirOr5-9E85",
"ObirOr5-9E86",
"ObirOr5-9E87",
"ObirOr5-9E88",
"ObirOr5-9E89",
"ObirOr5-9E9",
"ObirOr5-9E90",
"ObirOr5-9E91",
"ObirOr5-9E92",
"ObirOr5-9E93",
"ObirOr5-9E94",
"ObirOr5-9E95",
"ObirOr5-9E96",
"ObirOr5-9E97",
"ObirOr5-9E98",
"ObirOr5-9E99",
"ObirOr5-9Efrag1",
"ObirOr5-9Efrag2",
"ObirOr5-9Efrag3",
"ObirOr5-A1",
"ObirOr5-A2",
"ObirOr5-A3",
"ObirOr5-A4",
"ObirOr5-A5",
"ObirOr5-A6",
"ObirOr5-A7",
"ObirOr5-B1",
"ObirOr5-C1",
"ObirOr5-D1",
"ObirOr5-D2",
"ObirOr5-E10",
"ObirOr5-E11",
"ObirOr5-E12",
"ObirOr5-E13",
"ObirOr5-E14",
"ObirOr5-E15",
"ObirOr5-E16",
"ObirOr5-E17",
"ObirOr5-E18",
"ObirOr5-E19",
"ObirOr5-E1PSE",
"ObirOr5-E20",
"ObirOr5-E21",
"ObirOr5-E22",
"ObirOr5-E23",
"ObirOr5-E24",
"ObirOr5-E25",
"ObirOr5-E26",
"ObirOr5-E2PSE",
"ObirOr5-E3",
"ObirOr5-E4",
"ObirOr5-E5",
"ObirOr5-E6",
"ObirOr5-E7",
"ObirOr5-E8",
"ObirOr5-E9",
"ObirOr5-F1",
"ObirOr5-G1",
"ObirOr5-H1",
"ObirOr5-H2",
"ObirOr5-H3",
"ObirOr5-H4PSE",
"ObirOr5-H5",
"ObirOr5-H6PSE",
"ObirOr5-Hfrag1",
"ObirOr5-I1",
"ObirOr5-J1",
"ObirOr5-J2PSE",
"ObirOr5-J3",
"ObirOr5-K1",
"ObirOr5-K2",
"ObirOr5-L10",
"ObirOr5-L11",
"ObirOr5-L12",
"ObirOr5-L13",
"ObirOr5-L14",
"ObirOr5-L15",
"ObirOr5-L16",
"ObirOr5-L17PSE",
"ObirOr5-L18",
"ObirOr5-L19PSE",
"ObirOr5-L1PSE",
"ObirOr5-L2",
"ObirOr5-L20",
"ObirOr5-L21PSE",
"ObirOr5-L22",
"ObirOr5-L23",
"ObirOr5-L24PSE",
"ObirOr5-L25",
"ObirOr5-L26",
"ObirOr5-L27",
"ObirOr5-L28",
"ObirOr5-L29",
"ObirOr5-L3",
"ObirOr5-L30",
"ObirOr5-L31",
"ObirOr5-L32",
"ObirOr5-L33",
"ObirOr5-L34",
"ObirOr5-L35",
"ObirOr5-L4",
"ObirOr5-L5",
"ObirOr5-L6",
"ObirOr5-L7",
"ObirOr5-L8",
"ObirOr5-L9",
"ObirOr5-M1",
"ObirOr5-M2",
"ObirOr5-N1",
"ObirOr5-N2",
"ObirOr5-N3",
"ObirOr5-N4PSE",
"ObirOr5-O1",
"ObirOr5-O2",
"ObirOr5-O3",
"ObirOr5-Orco",
"ObirOr5-P1",
"ObirOr5-P2",
"ObirOr5-P3PSE",
"ObirOr5-P4",
"ObirOr5-P5",
"ObirOr5-P6",
"ObirOr5-P7",
"ObirOr5-Q1",
"ObirOr5-Q2",
"ObirOr5-Q3",
"ObirOr5-R1PSE",
"ObirOr5-R2",
"ObirOr5-R3",
"ObirOr5-R4PSE",
"ObirOr5-S1PSE",
"ObirOr5-T1",
"ObirOr5-T2",
"ObirOr5-T3",
"ObirOr5-U1",
"ObirOr5-U10",
"ObirOr5-U11",
"ObirOr5-U12",
"ObirOr5-U13",
"ObirOr5-U14",
"ObirOr5-U15",
"ObirOr5-U16",
"ObirOr5-U17",
"ObirOr5-U18",
"ObirOr5-U19PSE",
"ObirOr5-U2",
"ObirOr5-U20",
"ObirOr5-U21",
"ObirOr5-U22",
"ObirOr5-U23",
"ObirOr5-U24",
"ObirOr5-U25",
"ObirOr5-U26PSE",
"ObirOr5-U27",
"ObirOr5-U28",
"ObirOr5-U29",
"ObirOr5-U3",
"ObirOr5-U30PSE",
"ObirOr5-U31",
"ObirOr5-U32",
"ObirOr5-U33",
"ObirOr5-U34",
"ObirOr5-U35",
"ObirOr5-U36",
"ObirOr5-U37",
"ObirOr5-U38",
"ObirOr5-U39",
"ObirOr5-U4",
"ObirOr5-U40",
"ObirOr5-U41PSE",
"ObirOr5-U42",
"ObirOr5-U43",
"ObirOr5-U44",
"ObirOr5-U45",
"ObirOr5-U46PSE",
"ObirOr5-U47",
"ObirOr5-U48",
"ObirOr5-U49PSE",
"ObirOr5-U5",
"ObirOr5-U50",
"ObirOr5-U51",
"ObirOr5-U52",
"ObirOr5-U53HET",
"ObirOr5-U54",
"ObirOr5-U55",
"ObirOr5-U56",
"ObirOr5-U57",
"ObirOr5-U58",
"ObirOr5-U59",
"ObirOr5-U6",
"ObirOr5-U60HET",
"ObirOr5-U61",
"ObirOr5-U62",
"ObirOr5-U63",
"ObirOr5-U64",
"ObirOr5-U65",
"ObirOr5-U67",
"ObirOr5-U7",
"ObirOr5-U8",
"ObirOr5-U9",
"ObirOr5-Ufrag1",
"ObirOr5-V1",
"ObirOr5-V10",
"ObirOr5-V11",
"ObirOr5-V12PSE",
"ObirOr5-V13",
"ObirOr5-V14",
"ObirOr5-V15",
"ObirOr5-V16",
"ObirOr5-V17",
"ObirOr5-V18",
"ObirOr5-V19PSE",
"ObirOr5-V20PSE",
"ObirOr5-V21",
"ObirOr5-V22",
"ObirOr5-V23",
"ObirOr5-V24",
"ObirOr5-V25",
"ObirOr5-V26",
"ObirOr5-V27",
"ObirOr5-V28",
"ObirOr5-V2PSE",
"ObirOr5-V3",
"ObirOr5-V4",
"ObirOr5-V5",
"ObirOr5-V6",
"ObirOr5-V7",
"ObirOr5-V8",
"ObirOr5-V9",
"ObirOr5-W1",
"ObirOr5-X1",
"ObirOr5-X2PSE",
"ObirOr5-X3PSE",
"ObirOr5-XA1",
"ObirOr5-Y1",
"ObirOr5-ZA1")


```

